# Generated by Django 6.0 on 2026-03-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('normalized_url', models.URLField(blank=True)),
                ('verdict', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('report_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
