# Generated by Django 5.2.12 on 2026-04-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_portscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('scam_type', models.CharField(choices=[('website', 'Website / Phishing Link'), ('qr_code', 'QR Code Scam'), ('sms', 'SMS / Text Message'), ('phone', 'Phone Call'), ('email', 'Email Scam'), ('social', 'Social Media'), ('payment', 'Payment / UPI Fraud'), ('other', 'Other')], default='other', max_length=20)),
                ('scam_source', models.CharField(blank=True, help_text='URL, phone number, or entity that scammed you', max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scanner.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
